[phases.install]
commands = [
  "npm install --prefix server",
  "npm install --prefix client"
]

[phases.build]
commands = [
  "npm run build --prefix client"
]

[phases.start]
commands = [
  "node server/server.js"
]
