[phases.install]
commands = [
  "cd client && npm install",
  "cd server && npm install"
]

[phases.build]
commands = [
  "cd client && npm run build"
]

[phases.start]
commands = [
  "cd server && node server.js"
]

[[phases.build.environment]]
key = "NODE_ENV"
value = "production"